services:
  - type: web
    name: thibitisha-ai-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    scaling:
      minInstances: 1
      maxInstances: 1