services:
  - type: web
    name: telegram-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python clean_ai_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false